version: '3'
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: marvel_nginx
    ports: 
      - "8080:80"
    volumes:
      - ./application:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app
    networks:
      - app-network

  app:
    build:
      context: ./
      dockerfile: docker/php/app.dockerfile
    container_name: marvel_api
    volumes: 
      - ./application:/var/www
    networks:
      - app-network
      
  redis-server:
    image: "redis:alpine"
    container_name: app_redis
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: "bridge"
