version: '3'
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: marvel_nginx
    ports: 
      - "8080:80"
    volumes:
      - ./application:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app

  app:
    build:
      context: ./
      dockerfile: docker/php/app.dockerfile
    container_name: marvel_api
    volumes: 
      - ./application:/var/www
      
  redis-server:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
